name: bot

on:
  pull_request:
    paths:
      - tasks/**
      - src/**
      - tests/**
      - '*.json'
      - '*.yaml'
      - .github/workflows/bot.yaml

concurrency:
  cancel-in-progress: true
  group: ${{ github.workflow }}--${{ github.event.pull_request.id }}--${{ github.actor }}

jobs:
  run:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4.4.0
        with:
          node-version: 20
      - run: npm install -g pnpm@latest-10
      - run: pnpm i
      - run: pnpm build

      - uses: actions/create-github-app-token@df432ceedc7162793a195dd1713ff69aefc7379e # v2.0.6
        id: token
        with:
          app-id: ${{ secrets.BOT_APP_ID }}
          private-key: ${{ secrets.BOT_APP_PRIVATE_KEY }}
          owner: ${{ github.repository_owner }}
      - name: Run int128/actions-tanpopo
        uses: ./
        with:
          token: ${{ steps.token.outputs.token }}
        env:
          BOT_GEMINI_API_KEY: ${{ secrets.BOT_GEMINI_API_KEY }}
